### PR TITLE
Display interfaces which are assigned to the 'default' zone

### PR DESCRIPTION
**Pull request by imobachgs**
set-default-zone

### CODE REVIEW

**Comment by teclator** [comment]
Well, not sure about this fix, the interfaces are not assigned explicitly.

**Comment by imobachgs** [comment]
> Well, not sure about this fix as the interfaces are not assigned explicitly and we are working with the permanent configuration.

Sorry, I am not sure about what you are talking about. The idea is that, when you assign an interface to the "Default" zone, I would expect it to be changed when you change the "Default" one.

For instance, you assign `eth0` to the `Default` zone which is `public`. Then, you set `home` as the default zone. I would expect `eth0` to be assigned them to `home` as it is now the default zone.

But most probably I am missing some detail.

**Comment by teclator** [comment]
That is completely right. What I'm saying is that them are not assigning explicitly to the "home" zone but to the default or not zone at all.

**Comment by imobachgs** [comment]
Yes, and as a user, I expect those interfaces to listed there. But I see your point now. Perhaps we could add some indication so the user knows that those interfaces are there because they were assigned to the default zone.

**Comment by teclator** [comment]
Something to be discussed with Ken, and probably for SP1 once we get some feedback. Maybe we could add in the help each zone description, but that is just an idea.

**Pull request merged**
